# ! Load Character Data

# Warrior 
WARRIOR_SIZE = 162
WARRIOR_SCALE = 4
WARRIOR_OFFSET = [72, 56]
WARRIOR_SPEED = 10
WARRIOR_JUMP_HEIGHT = 30
WARRIOR_ATTACK1_RANGE = [100,200] # [x, y]
WARRIOR_ATTACK2_RANGE = [100,100]
WARRIOR_DATA = [WARRIOR_SIZE, WARRIOR_SCALE, WARRIOR_OFFSET, WARRIOR_SPEED, WARRIOR_JUMP_HEIGHT, WARRIOR_ATTACK1_RANGE, WARRIOR_ATTACK2_RANGE]
# Sorcerer SORCERER
SORCERER_SIZE = 250
SORCERER_SCALE = 3
SORCERER_OFFSET = [112, 110]
SORCERER_SPEED = 5
SORCERER_JUMP_HEIGHT = 30
SORCERER_ATTACK1_RANGE = [200,200]
SORCERER_ATTACK2_RANGE = [300,600]
SORCERER_DATA = [SORCERER_SIZE, SORCERER_SCALE, SORCERER_OFFSET, SORCERER_SPEED, SORCERER_JUMP_HEIGHT, SORCERER_ATTACK1_RANGE, SORCERER_ATTACK2_RANGE]
# Huntress
HUNTRESS_SIZE = 162
HUNTRESS_SCALE = 4
HUNTRESS_OFFSET = [72, 56]
HUNTRESS_SPEED = 12
HUNTRESS_JUMP_HEIGHT = 30
HUNTRESS_ATTACK1_RANGE = 0
HUNTRESS_ATTACK2_RANGE = 0
HUNTRESS_DATA = [HUNTRESS_SIZE, HUNTRESS_SCALE, HUNTRESS_OFFSET, HUNTRESS_SPEED, HUNTRESS_JUMP_HEIGHT]
# Old Wizard
OLD_WIZARD_SIZE = 162
OLD_WIZARD_SCALE = 4
OLD_WIZARD_OFFSET = [72, 56]
OLD_WIZARD_SPEED = 8
OLD_WIZARD_JUMP_HEIGHT = 30
OLD_WIZARD_ATTACK1_RANGE = 0
OLD_WIZARD_ATTACK2_RANGE = 0
OLD_WIZARD_DATA = [OLD_WIZARD_SIZE, OLD_WIZARD_SCALE, OLD_WIZARD_OFFSET, OLD_WIZARD_SPEED, OLD_WIZARD_JUMP_HEIGHT]